### ISSUE TITLE
Many types are incorrectly set as `any`

### ISSUE THREAD

**Issue by benmneb** [benmneb/mui-image#19]
It would appear that all the types for this package https://www.npmjs.com/package/@types/mui-image written as `React.CSSProperties['whatever it is']` dont actually work. They just come through as `any`.

[StackBlitz example](https://stackblitz.com/edit/react-ts-bix8pg?file=App.tsx).

Anyone know how to fix this? I was trying to avoid manually copying and pasting them all in.

**Comment by n3m** [comment]
![image](https://user-images.githubusercontent.com/36679293/202964303-389c5756-3377-41d4-801f-96f5b05b7baf.png)

Working just fine for me, BUT, I have...

` devDependency: "@types/mui-image": "^1.0.1",`

...in my `package.json`, perhaps that's whats missing in your StackBlitz?

**Comment by benmneb** [comment]
thanks for commenting! i have that package in the blitz, so i dont know why its not working there (or in codesandbox). but i just made a local project and everything is fine there, so i guess its a blitz/sandbox thing. the same project in vscode.dev doesnt show the typescript errors either 🤷 thanks again
