### ISSUE TITLE
How do I force an <Image> to show animations when 'src' attribute has been changed? 

### ISSUE THREAD

**Issue by flandia** [benmneb/mui-image#6]
Hi! 
I noticed that the Demo (https://mui-image.surge.sh/) uses the following to change to a new image
```
setShowPhoto(false);
setCurrentPhoto(newPhoto);
setTimeout(() => {
  setShowPhoto(true);
}, 100);
```
I am wondering whether it is the only way to achieve this, because it doesn't look very elegant...

**Comment by benmneb** [comment]
I'm sure it's not the only way, but it's the easiest way I could think of. Don't forget the `{showPhoto && <Image ... /> }` conditional rendering bit as well. (Though it's [better to use a ternary operator](https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx) than what I did here.)

**Comment by flandia** [comment]
@benmneb Thanks!
