### ISSUE TITLE
Question about License

### ISSUE THREAD

**Issue by sebastianfrey** [benmneb/mui-image#7]
Hi,

First of all. Nice Work =). Appart from that, it seems that there is no LICENSE file provided.

So my question: Under which licence is this library published?

**Comment by sebastianfrey** [comment]
Ah, I've overseen the license description at the bottom of your README. Nevertheless a LICENSE file would be nice to have. =)

**Comment by benmneb** [comment]
[Here you go sir](https://github.com/benmneb/mui-image/commit/b04cd9a4441d71f4297693c8efee65bfaf8b3cba). Thanks for reminding me!
